version: '3'
services:
    my-db:
        image: mysql:5.7.22
        restart: always
        ports:
          - "3307:3306"
        environment:
          - MYSQL_DATABASE=core_db
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=admin
          - MYSQL_PASSWORD=admin
        volumes:
          - "./data/db/mysql:/var/lib/mysql"

    my-adminer:
        image: adminer
        restart: always
        ports:
          - "3308:8080"
        depends_on:
          - my-db
          
    my-phalcon-api:
        build: ./app
        restart: always
        ports:
          - "8080:80"
        volumes:
          - "./logs/nginx:/var/log/nginx"
          - "./app/src:/var/www/public"
        depends_on:
          - my-db
    
